name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner-os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.runner-os }}

    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      if: matrix.runner-os == 'ubuntu-latest'
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
        config-file: ./.github/codeql/codeql-config.yml

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: global.json

    - name: dotnet format
      run: dotnet format src/OctoshiftCLI.sln --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore src/OctoshiftCLI.sln

    - name: Build
      run: dotnet build src/OctoshiftCLI.sln --no-restore /p:TreatWarningsAsErrors=true

    - name: Unit Test
      run: dotnet test src/OctoshiftCLI.Tests/OctoshiftCLI.Tests.csproj --no-build --verbosity normal --logger:"junit;LogFilePath=unit-tests.xml" --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Copy Coverage To Predictable Location
      if: always() && matrix.runner-os == 'ubuntu-latest'
      run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: always() && matrix.runner-os == 'ubuntu-latest'
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    # This is used by the subsequent publish-test-results.yml
    - name: Upload Unit Test Results
      if: always() && matrix.runner-os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Unit Test Results
        path: src/OctoshiftCLI.Tests/unit-tests.xml

    # This is used by the subsequent publish-test-results.yml
    - name: Upload Code Coverage Report
      if: always() && matrix.runner-os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Code Coverage Report
        path: code-coverage-results.md
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      if: matrix.runner-os == 'ubuntu-latest'

  upload-event-file:
    runs-on: ubuntu-latest
    steps:
    # This is used by the subsequent publish-test-results.yaml
    - name: Upload Event File
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build ]
    environment: PUBLISH_RELEASE

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_NOTES_PAT }}
        fetch-depth: 0

    - name: Validate tag on main
      shell: pwsh
      run: |
        git checkout main
        $mainsha = $(git show-ref refs/heads/main --hash)
        $tagsha = $(git show-ref ${{ github.ref }} --hash)

        Write-Output "refs/heads/main: $mainsha"
        Write-Output "${{ github.ref }}: $tagsha"

        if ($mainsha -ne $tagsha) {
          Write-Error "tag must match HEAD of main"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: global.json

    - name: Build Artifacts
      run: ./publish.ps1
      shell: pwsh
      env:
        CLI_VERSION: ${{ github.ref }}

    - name: Create gh-gei Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./RELEASENOTES.md
        files: |
          ./dist/ado2gh.*.win-x64.zip
          ./dist/ado2gh.*.win-x86.zip
          ./dist/ado2gh.*.linux-x64.tar.gz
          ./dist/ado2gh.*.osx-x64.tar.gz
          ./dist/win-x64/gei-windows-amd64.exe
          ./dist/win-x86/gei-windows-386.exe
          ./dist/linux-x64/gei-linux-amd64
          ./dist/osx-x64/gei-darwin-amd64
    
    - name: Create gh-ado2gh Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./RELEASENOTES.md
        repository: github/gh-ado2gh
        token: ${{ secrets.PUBLISH_ADO2GH_TOKEN }}
        files: |
          ./dist/win-x86/ado2gh-windows-386.exe
          ./dist/win-x64/ado2gh-windows-amd64.exe
          ./dist/linux-x64/ado2gh-linux-amd64
          ./dist/osx-x64/ado2gh-darwin-amd64

    - name: Create gh-bbs2gh Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./RELEASENOTES.md
        repository: github/gh-bbs2gh
        token: ${{ secrets.PUBLISH_BBS2GH_TOKEN }}
        files: |
          ./dist/win-x86/bbs2gh-windows-386.exe
          ./dist/win-x64/bbs2gh-windows-amd64.exe
          ./dist/linux-x64/bbs2gh-linux-amd64
          ./dist/osx-x64/bbs2gh-darwin-amd64

    - name: Archive Release Notes
      shell: pwsh
      run: |
        $TAG_NAME = "${{ github.ref }}".Substring(10)
        Get-Content ./RELEASENOTES.md | Out-File -FilePath ./releasenotes/$TAG_NAME.md
        "" | Out-File ./RELEASENOTES.md
        
    - name: Update LATEST-VERSION.TXT
      shell: pwsh
      run: |
        $TAG_NAME = "${{ github.ref }}".Substring(10)
        $TAG_NAME | Out-File ./LATEST-VERSION.txt
        
    - name: Commit Release Notes and Version
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated commit of archived release notes and version file [skip ci]
        file_pattern: RELEASENOTES.md releasenotes/*.md LATEST-VERSION.txt
        branch: main
